DOMAIN = "broan"

DEFAULT_ADDRESS = "00"

SPEED_LOW = "low"
SPEED_MEDIUM = "medium"
SPEED_HIGH = "high"
SPEED_CODE_MAPPING = {
    SPEED_LOW: "01",
    SPEED_MEDIUM: "02",
    SPEED_HIGH: "03"
}

ORDERED_NAMED_FAN_SPEEDS = [SPEED_LOW, SPEED_MEDIUM, SPEED_HIGH]

PRESET_MODE_CHANGE = '换气'
PRESET_MODE_OUT = '排风'
PRESET_MODE_SMART = '智能'
PRESET_MODE_POWER = '强劲'
PRESET_MODE_SAVING = '省电'

PRESET_MODES_TO_NAME = {
    PRESET_MODE_CHANGE: "01",
    PRESET_MODE_OUT: "02",
    PRESET_MODE_SMART: "03",
    PRESET_MODE_POWER: "04",
    PRESET_MODE_SAVING: "05"
}
